Update project and implement select tests
eclipse-glsp/glsp-playwright pull request #7
Opened 2024-02-09 08:53 UTC by haydar-metin

## Description

This PR brings some necessary changes for the future:

1) Updates the used frameworks and introduces fixes to work with them:
- Theia-Playwright
- GLSP-Client
- Playwright
2) Restructures example tests to be more align with `GLSP-Client` project structure
3) Make `GLSP-Playwright` more defensive (e.g., more information, checks, vscode-setup)

Finally, test cases based for [select](https://github.com/eclipse-glsp/glsp-client/tree/master/packages/client/src/features/select) are implemented.

#### What it does

- Update folder structure to be similar to glsp-client
- Remove aliasing from example project
- Make access more defensive
- Introduce `*` type for models to allow for all types
- Fix failing tests due to ghost elements

#### How to test
 
Please prepare the project by reading the [README](https://github.com/eclipse-glsp/glsp-playwright/tree/main/examples/workflow-test#eclipse-glsp-playwright-example)
 
1) Run the tests as described there.

The `standalone` version succeeds all the thests.

Theia and VSCode fail the test:

```
    [...] › ../../tests/features/select/select.spec.ts:84:9 › The select feature › should allow to deselect a single element through a keybinding 
```

It seems that using `Escape` does not reset the `select` state.

#### Follow-ups

-

#### Changelog

- [x] This PR should be mentioned in the changelog
- [x] This PR introduces a breaking change (if yes, provide more details below for the changelog and the migration guide)

`GLSP-Playwright` follows a similar approach as `Theia-Playwright`. However, we do not require any `loader`. That means we can create our `*App` now directly.

Before
```
app = await GLSPApp.loadApp(WorkflowApp, {
    type: 'integration',
    integration
});
```

Now
```
app = new WorkflowApp({
    type: 'integration',
    integration
});
```

2024-02-21 10:32 UTC, tortmayr requested changes
Thanks for the update!
Code changes look good to me, I just have a few minor comments/suggestions.

However, there seems to be an issue with one of the newly added select test cases.
For me, in both the Theia and the VS Code integration the test `The select feature- should allow to deselect a single element through a keybinding` fails with a timeout.

Here is the error stack from Theia testing:

```console
Running 43 tests using 6 workers
  1) [theia] › ../../tests/features/select/select.spec.ts:84:9 › The select feature › should allow to deselect a single element through a keybinding 

    Test timeout of 30000ms exceeded.

    Error: locator.waitFor: Test ended.
    Call log:
      - waiting for locator('body').locator('div.sprotty').locator('[data-svg-metadata-type="graph"]').locator('svg.sprotty-graph').locator('.selected').first() to be detached
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>
      -   locator resolved to visible <g id="workflow-diagram_0_task0" transform="transla…>…</g>


      94 |         await page.keyboard.press('Escape');
      95 |
    > 96 |         await Promise.all((await graph.locate().locator(`.${Selectable.CSS}`).all()).map(l => l.waitFor({ state: 'detached' })));
         |                                                                                                 ^
      97 |
      98 |         const after = await graph.getModelElementsBySelector(`.${Selectable.CSS}`, PModelElement);
      99 |         expect(after).toHaveLength(0);

        at map (/home/tobias/Git/OpenSource/glsp/glsp-playwright/examples/workflow-test/tests/features/select/select.spec.ts:96:97)
        at /home/tobias/Git/OpenSource/glsp/glsp-playwright/examples/workflow-test/tests/features/select/select.spec.ts:96:86

  1 failed
    [theia] › ../../tests/features/select/select.spec.ts:84:9 › The select feature › should allow to deselect a single element through a keybinding 
```

2024-02-21 10:32 UTC, tortmayr commented on examples/workflow-test/package.json
>      "mvn-artifact-download": "5.1.0",
Pretty sure we don't need `mvn-artifact-download` as dependency anymore, since we consume the node-server variant from npm.

2024-02-21 10:32 UTC, tortmayr commented on packages/glsp-playwright/package.json
> -    "@theia/playwright": "^1.39.0"
Please also keep `@playwright/test` and `@theia/playwright` as peerDependencies.
They need to be present when the package is consumed from npm. So we should explicitly delcare them as `peerDependencies`.

2024-02-21 14:00 UTC, haydar-metin commented
@tortmayr:

Both of the tests fail because:

>    [...] › ../../tests/features/select/select.spec.ts:84:9 › The select feature › should allow to deselect a single element through a keybinding 
> It seems that using Escape does not reset the select state.

So, both of Theia and VSCode do not clear the selected state if the escape is clicked multiple times. If I remember correctly, that was implemented with the accessibility features.

2024-02-21 14:21 UTC, tortmayr commented
> @tortmayr:
> 
> Both of the tests fail because:
> 
> > [...] › ../../tests/features/select/select.spec.ts:84:9 › The select feature › should allow to deselect a single element through a keybinding
> > It seems that using Escape does not reset the select state.
> 
> So, both of Theia and VSCode do not clear the selected state if the escape is clicked multiple times. If I remember correctly, that was implemented with the accessibility features.

I see, if this behavior is part of the a11y feature we should deactivate the corresponding test for now.
This feaute is currently only active in the standalon workflow example as support for Theia/VSCode is not yet implemented.
See (https://github.com/eclipse-glsp/glsp/issues/1130 and https://github.com/eclipse-glsp/glsp/issues/1129)

2024-02-22 11:02 UTC, haydar-metin commented
- The failing tests will be now skipped for Theia / VSCode. 
- With the `env` [GLSP_SERVER_PLAYWRIGHT_MANAGED](https://github.com/eclipse-glsp/glsp-playwright/pull/7/files#diff-5cd412ddca95a92a982bb3ed3077b6ec6d7842b1f9df9b96a5290678a3611d70R3) we can now define that the server will be started externally.
- Fixed also the error notification triggered by Playwright by extracting the `webserver` and `projects` part of the config into custom files.

2024-02-22 15:37 UTC, tortmayr approved these changes
Thanks! Changes look good to me and should make it easier to setup
CI workflows for UI tests in the respective GLSP components repositories.
Nice job!

2024-02-22 15:38 UTC, merged